# Generated by Django 3.1.3 on 2020-11-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('url_variable', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='%/some_dir')),
            ],
        ),
    ]
