# Generated by Django 3.1.3 on 2020-11-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201129_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='resized_image',
            field=models.ImageField(blank=True, upload_to='resized_imgs', verbose_name='Последнее изменение'),
        ),
    ]
