# Generated by Django 3.1.3 on 2020-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userfile_resized_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='resized_image',
            field=models.ImageField(blank=True, null=True, upload_to='resized_imgs', verbose_name='Последнее изменение'),
        ),
    ]
